services:
  grpc-server:
    build: .
    container_name: grpc-server
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    expose:
      - "${SERVER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - grpc-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
      start_interval: 2s 
    networks:
      - grpc-network


volumes:
  postgres_data:

networks:
  grpc-network:
    driver: bridge